info:
  title: Comparing text
  version: 1.0.0

schemes:
  - https

produces:
  - application/json

# path:
#   /api:
#     get:
#       summary: Give the marks
#       operationId: compare
#       responses:
#         '200':
#           description: A successful response
#           schema:
#             type: json

runtime: custom
env: flex




# automatic_scaling:
#   target_cpu_utilization: 0.65
#   min_instances: 5
#   max_instances: 100
#   min_pending_latency: 30ms
#   max_pending_latency: automatic
#   max_concurrent_requests: 50